dist: trusty
language: python
python:
  - 3.6
addons:
  apt:
    packages:
      - language-pack-fr
      - libblas-dev
      - liblapack-dev
      - gfortran
      # chrome is required for selenium testing
      - chromium-chromedriver
env:
  - LBB_ENV=test DB_HOST=localhost DB_PORT=3036 DB_USER=travis DB_PASSWORD=""
cache: pip
services:
  - mysql
  - elasticsearch
before_install:
  - mysql -u travis -e 'CREATE DATABASE IF NOT EXISTS lbb_test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;'
install:
  - sudo locale-gen fr_FR
  - sudo update-locale
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.4.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.4.deb && sudo service elasticsearch restart
  - pip install -r requirements.txt
  - python setup.py develop
script:
  # Note that we could speed-up the build process by running different env values
  - nosetests --nologcapture labonneboite/tests/app
  - nosetests --nologcapture labonneboite/tests/web
  - nosetests --nologcapture labonneboite/tests/scripts
  - nosetests --nologcapture labonneboite/tests/importer
  # Integration
  - mysql -u travis -e 'DROP DATABASE IF EXISTS lbb_test;'
  - mysql -u travis -e 'CREATE DATABASE IF NOT EXISTS lbb_test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;'
  - alembic upgrade head
  - mysql -u travis lbb_test < ./labonneboite/alembic/sql/etablissements.sql
  - create_index --full
  - nosetests labonneboite/tests/integration
  # Selenium
  - mysql -u travis -e 'DROP DATABASE IF EXISTS lbb_test;'
  - mysql -u travis -e 'CREATE DATABASE IF NOT EXISTS lbb_test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;'
  - alembic upgrade head
  - mysql -u travis lbb_test < ./labonneboite/alembic/sql/etablissements.sql
  - create_index --full
  - nosetests labonneboite/tests/selenium
  # Build docker image
  - docker build .
