version: "3"
services:

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  # https://www.elastic.co/blog/how-to-make-a-dockerfile-for-elasticsearch
  elasticsearch:
    image: elasticsearch:1.7.2
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.name=lbb"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #restart: "unless-stopped"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      # TODO remap port
      - 9200:9200

  mysql:
    image: mysql:5.6.36
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3307:3306
